name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
        package:
          - {user: SciML, repo: DiffEqBase.jl, group: All}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      julia-version: "${{ matrix.julia-version }}"
      repo: "${{ matrix.package.repo }}"
      owner: "${{ matrix.package.user }}"
      group: "${{ matrix.package.group }}"
    secrets: "inherit"
